name: Rubik
author: gdotdesign
sources:
  - Source/Config.coffee
  - Source/Fx.Three.coffee
  - Source/Cube.coffee
  - Source/Scene.coffee
  - Source/Rubik.coffee
  - Source/Frontend.coffee
  - Source/Game.coffee
