MATERIAL = new THREE.MeshFaceMaterial()
STROKE_MATERIAL = new THREE.MeshColorStrokeMaterial 0x000000, 0.2 ,2
STROKE_MATERIAL2 = new THREE.MeshColorStrokeMaterial 0x000000, 0.9 ,5
MATERIAL_BLACK = new THREE.MeshColorFillMaterial( 0x000000, 0.8 )
CUBE_SIZE = 300
CUBE_MATERIALS = []
CUBE_MATERIALS['white'] = new THREE.MeshColorFillMaterial( 0xffffff, 1 )
CUBE_MATERIALS['red'] = new THREE.MeshColorFillMaterial( 0xff0000, 1 )
CUBE_MATERIALS['orange'] = new THREE.MeshColorFillMaterial( 0xFF6A00, 1 )
CUBE_MATERIALS['yellow'] = new THREE.MeshColorFillMaterial( 0xffff00, 1 )
CUBE_MATERIALS['blue'] = new THREE.MeshColorFillMaterial( 0x0000ff, 1 )
CUBE_MATERIALS['green'] = new THREE.MeshColorFillMaterial( 0x00ff00, 1 )
TweenDuration = 1250
Rubik = {}
